services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d
    networks:
      - app_network
    

  backend:
    image: thedjuke/backend:latest   
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app_network
    
  frontend:
    image: thedjuke/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./images:/images
      - ./nginx/users.htpasswd:/etc/nginx/users.htpasswd
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  
  

networks:
  app_network:
    driver: bridge
