services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./Data:/var/lib/mysql
      - ./mysql_config:/etc/mysql/conf.d
    networks:
      - app_network
    
  backend:
    image: thedjuke/backend:latest   
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app_network
    
  frontend:
    image: thedjuke/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network
    volumes:
      - ./images:/images

networks:
  app_network:
    driver: bridge

