name: Build and Deploy Docker Images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Angular Docker image
        run: |
          cd frontend
          docker build --no-cache -t frontend .
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:latest

      - name: Build Java Spring Docker image
        run: |
          cd backend
          docker build --no-cache -t backend .
          docker build --no-cache -t ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/backend:latest
          
      

